server:
  port: 8081
  servlet:
    context-path: /api

spring:
  jackson:
    date-format: dd/MM/yyyy
  data:
    mongodb:
      host: localhost
      port: 27017
      username: oauth-user
      password: password
      database: oauth-db
